### ISSUE TITLE
Using es.index.read.missing.as.empty returns an empty result if one out of many indices is missing

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#1055]
If a user specifies multiple indices and one of them is not found - if the `es.index.read.missing.as.empty` property is set to true, then the entire connector returns an empty result. Instead, the connector should skip the missing index and continue on with processing the rest of the provided indices.

**Comment by jbaiera** [comment]
More specifically: Setting `es.index.read.missing.as.empty` should set `ignore_unavailable` for the multi-index rest actions.

**Comment by Srinathc** [comment]
Facing this issue currently. Have two indices in my query path one of which doesn't exist. Inspite of setting es.index.read.missing.as.empty to true the connector returns an empty data frame. Would expect it to behave as if "ignore_unavailable" is specified.

**Comment by alrutten** [comment]
similar issue. Fetching data using spark-sql throws and exception when an index does not exist, in stead of continuing with the next index when `es.index.read.missing.as.empty` is set to `true`.

ES options:
`val elasticSearchOptions = Map(
		ConfigurationOptions.ES_NODES -> "node01, node02",
		ConfigurationOptions.ES_PORT -> esPort,
		ConfigurationOptions.ES_INDEX_AUTO_CREATE -> "yes",
		ConfigurationOptions.ES_RESOURCE_READ -> "graylog2_*",
		ConfigurationOptions.ES_INDEX_READ_MISSING_AS_EMPTY -> "true",
		//ConfigurationOptions.ES_READ_FIELD_EXCLUDE -> "streams",
		"pushdown" -> "true",
		ConfigurationOptions.ES_HTTP_TIMEOUT -> "10m",
		ConfigurationOptions.ES_SCROLL_KEEPALIVE -> "60m",
		ConfigurationOptions.ES_SCROLL_SIZE -> "10000",
		ConfigurationOptions.ES_MAPPING_DATE_RICH_OBJECT -> "false", // datetime will be read as Long,
		ConfigurationOptions.ES_MAX_DOCS_PER_PARTITION -> "1000000"

	)`

querying ES from spark:

`val log: DataFrame = EsSparkSQL.esDF(session, elasticSearchOptions)
log.cache()`

inconsistently runs into `org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: no such index`

i assume this happens when we get unlucky and the index gets deleted between spark querying ES, and actually fetching the data. Note: this is unrelated to whether the queried data is on the deleted index or not (it never was).

**Comment by larryzhu2018** [comment]
we continue to observe this issue. can you please provide a fix to this?

**Comment by masseyke** [comment]
I just merged a fix for this that will be in 8.5.0.

**Comment by larryzhu2018** [comment]
can you please provide the link to your fix? we can build it locally and try to test it for you.

**Comment by masseyke** [comment]
Yeah the pull request is at #1997.

**Comment by smokeriu** [comment]
> Yeah the pull request is at #1997.

Hello, I found that this parameter still doesn't work when I'm using reading ES version 6.x (on typed index). After viewing your PR, I noticed that you only modified the situation where the resource type does not exist. What was the reason for this? 

I tested this with es-head and found that it works with es version 6.5.x for indexes with type set as well.

Before: 
```
if (indexResource.isTyped()) {
        return getMappings(indexResource.index() + "/_mapping/" + indexResource.type(), true);
} else {
        return getMappings(indexResource.index() + "/_mapping", false);
}
```

After:
 ```
if (indexResource.isTyped()) {
        return getMappings(indexResource.index() + "/_mapping/" + indexResource.type(), true);
} else {
        return getMappings(indexResource.index() + "/_mapping" + (indexReadMissingAsEmpty ? "?ignore_unavailable=true" : ""), false);
}
```

Would a change to the following version be more compatible?
```
if (indexResource.isTyped()) {
        return getMappings(indexResource.index() + "/_mapping/" + indexResource.type() + (indexReadMissingAsEmpty ? "?ignore_unavailable=true" : ""), true);
} else {
        return getMappings(indexResource.index() + "/_mapping" + (indexReadMissingAsEmpty ? "?ignore_unavailable=true" : ""), false);
}
```
