### ISSUE TITLE
Not able to insert data into ES using elasticsearch-hadoop-2.1.0.Beta3.jar

### ISSUE THREAD

**Issue by mojaiq** [elastic/elasticsearch-hadoop#416]
I'm not able to insert data into ES using the elasticsearch-hadoop-2.1.0.Beta3.jar.
I'm running the following query from Beeswax UI:
```sql
DROP TABLE IF EXISTS search_sample_07_to_es;
CREATE EXTERNAL TABLE search_sample_07_to_es (code STRING, description STRING) STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler' TBLPROPERTIES('es.resource' = 'es_hadoop/productsample', 'es.nodes' = '<es host name>', 'es.port' = '<es port name>',  'es.write.operation' = 'index', 'es.index.auto.create' = 'yes' , 'es.net.http.auth.user' = '<es admin user>' ,'es.net.http.auth.pass' = '<es admin password>', 'es.index.read.missing.as.empty' = 'yes');

INSERT OVERWRITE TABLE search_sample_07_to_es SELECT sample_07.code, sample_07.description FROM sample_07;
```
I'm able to read from ES indexes into Hive without any issues. The write operation is where it is failing.

**Comment by jackx-wz** [comment]
me too，my ENV is hadoop-2.6.0  apache-hive-1.1.0 elasticsearch-hadoop-2.1.0.Beta3
and I have some error message:

Logs for container_1427896347070_0001_02_000001
2015-04-01 22:04:17,381 INFO [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Created MRAppMaster for application appattempt_1427896347070_0001_000002
2015-04-01 22:04:18,419 FATAL [main] org.apache.hadoop.conf.Configuration: error parsing conf job.xml
org.xml.sax.SAXParseException; systemId: file:///root/hadoop/tmp/nm-local-dir/usercache/root/appcache/application_1427896347070_0001/container_1427896347070_0001_02_000001/job.xml; lineNumber: 647; columnNumber: 51; 字符引用 "&#
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:150)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2183)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2252)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2205)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2112)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:1078)
	at org.apache.hadoop.mapreduce.v2.util.MRWebAppUtil.initialize(MRWebAppUtil.java:50)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1407)
2015-04-01 22:04:18,427 FATAL [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Error starting MRAppMaster
java.lang.RuntimeException: org.xml.sax.SAXParseException; systemId: file:///root/hadoop/tmp/nm-local-dir/usercache/root/appcache/application_1427896347070_0001/container_1427896347070_0001_02_000001/job.xml; lineNumber: 647; columnNumber: 51; 字符引用 "&#
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2348)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2205)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2112)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:1078)
	at org.apache.hadoop.mapreduce.v2.util.MRWebAppUtil.initialize(MRWebAppUtil.java:50)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1407)
Caused by: org.xml.sax.SAXParseException; systemId: file:///root/hadoop/tmp/nm-local-dir/usercache/root/appcache/application_1427896347070_0001/container_1427896347070_0001_02_000001/job.xml; lineNumber: 647; columnNumber: 51; 字符引用 "&#
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:150)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2183)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2252)
	... 5 more
2015-04-01 22:04:18,437 INFO [main] org.apache.hadoop.util.ExitUtil: Exiting with status 1

-----------------------------------------------------------
but I found if table only has one field this env is work! Hope to get help,Thx!!!

**Comment by costin** [comment]
In both cases I highly suggest using the latest version (the snapshot) since Hive 1.1, 1.0 and 0.14 broke backwards compatibility with older releases. See this [section](http://www.elastic.co/guide/en/elasticsearch/hadoop/master/install.html#download-dev) of the docs.
If the error, persists please provide more information as explained [here](http://www.elastic.co/guide/en/elasticsearch/hadoop/master/troubleshooting.html#help) such as the script you are trying to use and in particular the full error from the Hive logs.
The error posted is not complete and doesn't offer any useful information nor that the issue is related to Elasticsearch itself.

@jackx-wz Please, raise a separate issue, don't hijack existing ones. This issue (caused by Hive) has been fixed in the build above. See #359 and in particular [this](https://github.com/elastic/elasticsearch-hadoop/issues/409#issuecomment-88450289) comment from issue #409

**Comment by mojaiq** [comment]
I'm using Hive 0.13. I still tried running with the latest build snapshot and that did not resolve the problem.

Here is the Hive script I'm using (with server/port info stubbed). country_codes is an existing table in Hive/HDFS.
DROP TABLE IF EXISTS country_code_to_es;
CREATE EXTERNAL TABLE country_code_to_es (country_code STRING, country_name STRING) STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler' TBLPROPERTIES('es.resource' = 'es_hadoop/country', 'es.nodes' = '<host>', 'es.port' = <port>,  'es.write.operation' = 'index', 'es.index.auto.create' = 'yes' , 'es.net.http.auth.user' = <user>,'es.net.http.auth.pass' = <passwd>, 'es.index.read.missing.as.empty' = 'yes');
INSERT OVERWRITE TABLE country_code_to_es SELECT * FROM country_codes;

I'm able to read an existing index from ES into Hive without issues. The write operation is where it is failing. Attaching the complete logs. But I still only see generic errors in the logs..





15/04/06 22:29:41 INFO session.SessionState: No Tez session required at this point. hive.execution.engine=mr.
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=Driver.run from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=TimeToSubmit from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO ql.Driver: Concurrency mode is disabled, not creating a lock manager
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=compile from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=parse from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO parse.ParseDriver: Parsing command: use default
15/04/06 22:29:41 INFO parse.ParseDriver: Parse Completed
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=parse start=1428384581514 end=1428384581514 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=semanticAnalyze from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO ql.Driver: Semantic Analysis Completed
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=semanticAnalyze start=1428384581515 end=1428384581515 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO ql.Driver: Returning Hive schema: Schema(fieldSchemas:null, properties:null)
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=compile start=1428384581514 end=1428384581515 duration=1 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=Driver.execute from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO ql.Driver: Starting command: use default
15/04/06 22:29:41 INFO hooks.ATSHook: Created ATS Hook
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=PreHook.org.apache.hadoop.hive.ql.hooks.ATSHook from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=PreHook.org.apache.hadoop.hive.ql.hooks.ATSHook start=1428384581515 end=1428384581515 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=TimeToSubmit start=1428384581514 end=1428384581515 duration=1 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=runTasks from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=task.DDL.Stage-0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=runTasks start=1428384581515 end=1428384581523 duration=8 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO hooks.ATSHook: Created ATS Hook
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=PostHook.org.apache.hadoop.hive.ql.hooks.ATSHook from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=PostHook.org.apache.hadoop.hive.ql.hooks.ATSHook start=1428384581523 end=1428384581523 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=Driver.execute start=1428384581515 end=1428384581523 duration=8 from=org.apache.hadoop.hive.ql.Driver>
OK
15/04/06 22:29:41 INFO ql.Driver: OK
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=releaseLocks from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=releaseLocks start=1428384581524 end=1428384581524 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=Driver.run start=1428384581514 end=1428384581524 duration=10 from=org.apache.hadoop.hive.ql.Driver>
converting to local hdfs://<server>/user/hue/elasticsearch-hadoop-2.1.0.BUILD.jar
15/04/06 22:29:41 INFO SessionState: converting to local hdfs://<server>/user/hue/elasticsearch-hadoop-2.1.0.BUILD.jar
Added /tmp/49eabaa2-8d58-4f0f-b30f-36c07124fc05_resources/elasticsearch-hadoop-2.1.0.BUILD.jar to class path
15/04/06 22:29:41 INFO SessionState: Added /tmp/49eabaa2-8d58-4f0f-b30f-36c07124fc05_resources/elasticsearch-hadoop-2.1.0.BUILD.jar to class path
Added resource: /tmp/49eabaa2-8d58-4f0f-b30f-36c07124fc05_resources/elasticsearch-hadoop-2.1.0.BUILD.jar
15/04/06 22:29:41 INFO SessionState: Added resource: /tmp/49eabaa2-8d58-4f0f-b30f-36c07124fc05_resources/elasticsearch-hadoop-2.1.0.BUILD.jar
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=compile from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=parse from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO parse.ParseDriver: Parsing command: CREATE EXTERNAL TABLE country_code_to_es (
    country_code STRING, 
    country_name STRING) 
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler' 
TBLPROPERTIES('es.resource' = 'es_hadoop/country', 
              'es.nodes' = '<server>', 
              'es.port' = '<port>',  
              'es.write.operation' = 'index', 
              'es.index.auto.create' = 'yes' , 
              'es.net.http.auth.user' = '<user>' ,
              'es.net.http.auth.pass' = '<passwd>', 
              'es.index.read.missing.as.empty' = 'yes')
15/04/06 22:29:41 INFO parse.ParseDriver: Parse Completed
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=parse start=1428384581680 end=1428384581680 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=semanticAnalyze from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO parse.SemanticAnalyzer: Starting Semantic Analysis
15/04/06 22:29:41 INFO parse.SemanticAnalyzer: Creating table country_code_to_es position=22
15/04/06 22:29:41 INFO ql.Driver: Semantic Analysis Completed
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=semanticAnalyze start=1428384581680 end=1428384581699 duration=19 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO ql.Driver: Returning Hive schema: Schema(fieldSchemas:null, properties:null)
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=compile start=1428384581679 end=1428384581699 duration=20 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO hive.metastore: Trying to connect to metastore with URI thrift://<server>
15/04/06 22:29:41 INFO hive.metastore: Connected to metastore.
15/04/06 22:29:41 INFO session.SessionState: No Tez session required at this point. hive.execution.engine=mr.
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=Driver.execute from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO ql.Driver: Starting command: CREATE EXTERNAL TABLE country_code_to_es (
    country_code STRING, 
    country_name STRING) 
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler' 
TBLPROPERTIES('es.resource' = 'es_hadoop/country', 
              'es.nodes' = '<server>', 
              'es.port' = '<port>',  
              'es.write.operation' = 'index', 
              'es.index.auto.create' = 'yes' , 
              'es.net.http.auth.user' = '<user>' ,
              'es.net.http.auth.pass' = '<password>', 
              'es.index.read.missing.as.empty' = 'yes')
15/04/06 22:29:41 INFO hooks.ATSHook: Created ATS Hook
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=PreHook.org.apache.hadoop.hive.ql.hooks.ATSHook from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=PreHook.org.apache.hadoop.hive.ql.hooks.ATSHook start=1428384581703 end=1428384581703 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=TimeToSubmit start=1428384581514 end=1428384581703 duration=189 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=runTasks from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=task.DDL.Stage-0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO exec.DDLTask: Use StorageHandler-supplied org.elasticsearch.hadoop.hive.EsSerDe for table country_code_to_es
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=runTasks start=1428384581704 end=1428384581763 duration=59 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO hooks.ATSHook: Created ATS Hook
15/04/06 22:29:41 INFO log.PerfLogger: <PERFLOG method=PostHook.org.apache.hadoop.hive.ql.hooks.ATSHook from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=PostHook.org.apache.hadoop.hive.ql.hooks.ATSHook start=1428384581763 end=1428384581763 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:29:41 INFO log.PerfLogger: </PERFLOG method=Driver.execute start=1428384581703 end=1428384581763 duration=60 from=org.apache.hadoop.hive.ql.Driver>
OK
15/04/06 22:29:41 INFO ql.Driver: OK
15/04/06 22:29:43 INFO session.SessionState: No Tez session required at this point. hive.execution.engine=mr.


15/04/06 22:30:41 INFO session.SessionState: No Tez session required at this point. hive.execution.engine=mr.
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=Driver.run from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=TimeToSubmit from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO ql.Driver: Concurrency mode is disabled, not creating a lock manager
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=compile from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=parse from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO parse.ParseDriver: Parsing command: use default
15/04/06 22:30:41 INFO parse.ParseDriver: Parse Completed
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=parse start=1428384641720 end=1428384641720 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=semanticAnalyze from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO ql.Driver: Semantic Analysis Completed
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=semanticAnalyze start=1428384641720 end=1428384641720 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO ql.Driver: Returning Hive schema: Schema(fieldSchemas:null, properties:null)
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=compile start=1428384641720 end=1428384641720 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=Driver.execute from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO ql.Driver: Starting command: use default
15/04/06 22:30:41 INFO hooks.ATSHook: Created ATS Hook
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=PreHook.org.apache.hadoop.hive.ql.hooks.ATSHook from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=PreHook.org.apache.hadoop.hive.ql.hooks.ATSHook start=1428384641721 end=1428384641721 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=TimeToSubmit start=1428384641719 end=1428384641721 duration=2 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=runTasks from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=task.DDL.Stage-0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=runTasks start=1428384641721 end=1428384641725 duration=4 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO hooks.ATSHook: Created ATS Hook
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=PostHook.org.apache.hadoop.hive.ql.hooks.ATSHook from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=PostHook.org.apache.hadoop.hive.ql.hooks.ATSHook start=1428384641726 end=1428384641726 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=Driver.execute start=1428384641720 end=1428384641726 duration=6 from=org.apache.hadoop.hive.ql.Driver>
OK
15/04/06 22:30:41 INFO ql.Driver: OK
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=releaseLocks from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=releaseLocks start=1428384641726 end=1428384641726 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=Driver.run start=1428384641719 end=1428384641726 duration=7 from=org.apache.hadoop.hive.ql.Driver>
converting to local hdfs://<server>/user/hue/elasticsearch-hadoop-2.1.0.BUILD.jar
15/04/06 22:30:41 INFO SessionState: converting to local hdfs://<server>/user/hue/elasticsearch-hadoop-2.1.0.BUILD.jar
Added /tmp/7bd96b68-fef6-4218-9d3d-7259f91fc095_resources/elasticsearch-hadoop-2.1.0.BUILD.jar to class path
15/04/06 22:30:41 INFO SessionState: Added /tmp/7bd96b68-fef6-4218-9d3d-7259f91fc095_resources/elasticsearch-hadoop-2.1.0.BUILD.jar to class path
Added resource: /tmp/7bd96b68-fef6-4218-9d3d-7259f91fc095_resources/elasticsearch-hadoop-2.1.0.BUILD.jar
15/04/06 22:30:41 INFO SessionState: Added resource: /tmp/7bd96b68-fef6-4218-9d3d-7259f91fc095_resources/elasticsearch-hadoop-2.1.0.BUILD.jar
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=compile from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=parse from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO parse.ParseDriver: Parsing command: INSERT OVERWRITE TABLE country_code_to_es SELECT * FROM country_codes
15/04/06 22:30:41 INFO parse.ParseDriver: Parse Completed
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=parse start=1428384641859 end=1428384641860 duration=1 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=semanticAnalyze from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO parse.SemanticAnalyzer: Starting Semantic Analysis
15/04/06 22:30:41 INFO parse.SemanticAnalyzer: Completed phase 1 of Semantic Analysis
15/04/06 22:30:41 INFO parse.SemanticAnalyzer: Get metadata for source tables
15/04/06 22:30:41 INFO parse.SemanticAnalyzer: Get metadata for subqueries
15/04/06 22:30:41 INFO parse.SemanticAnalyzer: Get metadata for destination tables
15/04/06 22:30:41 INFO parse.SemanticAnalyzer: Completed getting MetaData in Semantic Analysis
15/04/06 22:30:41 INFO exec.Utilities: Create dirs hdfs://<server>/tmp/hive-beeswax-hue/hive_2015-04-06_22-30-41_859_5483443401670875199-406 with permission rwxrwxrwx recursive false
15/04/06 22:30:41 INFO parse.SemanticAnalyzer: Set stats collection dir : hdfs://<server>/tmp/hive-beeswax-hue/hive_2015-04-06_22-30-41_859_5483443401670875199-406/-ext-10000
15/04/06 22:30:41 INFO ppd.OpProcFactory: Processing for FS(62112)
15/04/06 22:30:41 INFO ppd.OpProcFactory: Processing for SEL(62111)
15/04/06 22:30:41 INFO ppd.OpProcFactory: Processing for TS(62110)
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=partition-retrieving from=org.apache.hadoop.hive.ql.optimizer.ppr.PartitionPruner>
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=partition-retrieving start=1428384641909 end=1428384641909 duration=0 from=org.apache.hadoop.hive.ql.optimizer.ppr.PartitionPruner>
15/04/06 22:30:41 INFO physical.MetadataOnlyOptimizer: Looking for table scans where optimization is applicable
15/04/06 22:30:41 INFO physical.MetadataOnlyOptimizer: Found 0 metadata only table scans
15/04/06 22:30:41 INFO physical.Vectorizer: Input format: org.apache.hadoop.mapred.TextInputFormat, doesn't provide vectorized input
15/04/06 22:30:41 INFO parse.SemanticAnalyzer: Completed plan generation
15/04/06 22:30:41 INFO ql.Driver: Semantic Analysis Completed
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=semanticAnalyze start=1428384641860 end=1428384641912 duration=52 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO ql.Driver: Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:country_codes.country_code, type:string, comment:null), FieldSchema(name:country_codes.country_name, type:string, comment:null)], properties:null)
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=compile start=1428384641859 end=1428384641913 duration=54 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO hive.metastore: Trying to connect to metastore with URI thrift://<server>
15/04/06 22:30:41 INFO hive.metastore: Connected to metastore.
15/04/06 22:30:41 INFO session.SessionState: No Tez session required at this point. hive.execution.engine=mr.
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=Driver.execute from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO ql.Driver: Starting command: INSERT OVERWRITE TABLE country_code_to_es SELECT * FROM country_codes
15/04/06 22:30:41 INFO hooks.ATSHook: Created ATS Hook
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=PreHook.org.apache.hadoop.hive.ql.hooks.ATSHook from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=PreHook.org.apache.hadoop.hive.ql.hooks.ATSHook start=1428384641916 end=1428384641917 duration=1 from=org.apache.hadoop.hive.ql.Driver>
Query ID = hue_20150406223030_0fa48297-19cd-45bd-aeac-0d2a349c62a3
15/04/06 22:30:41 INFO ql.Driver: Query ID = hue_20150406223030_0fa48297-19cd-45bd-aeac-0d2a349c62a3
Total jobs = 1
15/04/06 22:30:41 INFO ql.Driver: Total jobs = 1
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=TimeToSubmit start=1428384641719 end=1428384641918 duration=199 from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=runTasks from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=task.MAPRED.Stage-0 from=org.apache.hadoop.hive.ql.Driver>
Launching Job 1 out of 1
15/04/06 22:30:41 INFO ql.Driver: Launching Job 1 out of 1
Number of reduce tasks is set to 0 since there's no reduce operator
15/04/06 22:30:41 INFO exec.Task: Number of reduce tasks is set to 0 since there's no reduce operator
15/04/06 22:30:41 INFO exec.Utilities: Create dirs hdfs://<server>/tmp/hive-beeswax-hue/hive_2015-04-06_22-30-41_859_5483443401670875199-703 with permission rwxrwxrwx recursive false
15/04/06 22:30:41 INFO ql.Context: New scratch dir is hdfs://<server>/tmp/hive-beeswax-hue/hive_2015-04-06_22-30-41_859_5483443401670875199-703
15/04/06 22:30:41 INFO mr.ExecDriver: Using org.apache.hadoop.hive.ql.io.CombineHiveInputFormat
15/04/06 22:30:41 INFO mr.ExecDriver: adding libjars: file:///tmp/7bd96b68-fef6-4218-9d3d-7259f91fc095_resources/elasticsearch-hadoop-2.1.0.BUILD.jar
15/04/06 22:30:41 INFO exec.Utilities: Processing alias country_codes
15/04/06 22:30:41 INFO exec.Utilities: Adding input file hdfs://<server>/apps/hive/warehouse/country_codes
15/04/06 22:30:41 INFO exec.Utilities: Content Summary not cached for hdfs://<server>/apps/hive/warehouse/country_codes
15/04/06 22:30:41 INFO ql.Context: New scratch dir is hdfs://<server>/tmp/hive-beeswax-hue/hive_2015-04-06_22-30-41_859_5483443401670875199-703
15/04/06 22:30:41 INFO log.PerfLogger: <PERFLOG method=serializePlan from=org.apache.hadoop.hive.ql.exec.Utilities>
15/04/06 22:30:41 INFO exec.Utilities: Serializing MapWork via kryo
15/04/06 22:30:41 INFO log.PerfLogger: </PERFLOG method=serializePlan start=1428384641958 end=1428384641981 duration=23 from=org.apache.hadoop.hive.ql.exec.Utilities>
15/04/06 22:30:42 INFO impl.TimelineClientImpl: Timeline service address: http://<server>/ws/v1/timeline/
15/04/06 22:30:42 INFO client.RMProxy: Connecting to ResourceManager at <server>
15/04/06 22:30:42 INFO exec.Utilities: Create dirs hdfs://<server>/apps/hive/warehouse/_tmp.country_code_to_es with permission rwxrwxrwx recursive false
15/04/06 22:30:42 INFO impl.TimelineClientImpl: Timeline service address: http://<server>/ws/v1/timeline/
15/04/06 22:30:42 INFO client.RMProxy: Connecting to ResourceManager at <server>
15/04/06 22:30:42 INFO exec.Utilities: No plan file found: hdfs://<server>/tmp/hive-beeswax-hue/hive_2015-04-06_22-30-41_859_5483443401670875199-703/-mr-10002/640618c2-7e36-4b5f-a9d8-013d7943dceb/reduce.xml
15/04/06 22:30:42 INFO mr.EsOutputFormat: Writing to [es_hadoop/country]
15/04/06 22:30:42 WARN mapreduce.JobSubmitter: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
15/04/06 22:30:42 INFO log.PerfLogger: <PERFLOG method=getSplits from=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat>
15/04/06 22:30:42 INFO io.CombineHiveInputFormat: CombineHiveInputSplit creating pool for hdfs://<server>/apps/hive/warehouse/country_codes; using filter path hdfs://<server>/apps/hive/warehouse/country_codes
15/04/06 22:30:42 INFO input.FileInputFormat: Total input paths to process : 1
15/04/06 22:30:42 INFO input.CombineFileInputFormat: DEBUG: Terminated node allocation with : CompletedNodes: 2, size left: 0
15/04/06 22:30:42 INFO io.CombineHiveInputFormat: number of splits 1
15/04/06 22:30:42 INFO log.PerfLogger: </PERFLOG method=getSplits start=1428384642528 end=1428384642536 duration=8 from=org.apache.hadoop.hive.ql.io.CombineHiveInputFormat>
15/04/06 22:30:42 INFO mapreduce.JobSubmitter: number of splits:1
15/04/06 22:30:42 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1427108893685_8230
15/04/06 22:30:42 INFO impl.YarnClientImpl: Submitted application application_1427108893685_8230
15/04/06 22:30:42 INFO mapreduce.Job: The url to track the job: http://<server>/proxy/application_1427108893685_8230/
Starting Job = job_1427108893685_8230, Tracking URL = http://<server>/proxy/application_1427108893685_8230/
15/04/06 22:30:42 INFO exec.Task: Starting Job = job_1427108893685_8230, Tracking URL = http://<server>/proxy/application_1427108893685_8230/
Kill Command = /usr/lib/hadoop/bin/hadoop job  -kill job_1427108893685_8230
15/04/06 22:30:42 INFO exec.Task: Kill Command = /usr/lib/hadoop/bin/hadoop job  -kill job_1427108893685_8230
Hadoop job information for Stage-0: number of mappers: 0; number of reducers: 0
15/04/06 22:30:47 INFO exec.Task: Hadoop job information for Stage-0: number of mappers: 0; number of reducers: 0
15/04/06 22:30:47 WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
2015-04-06 22:30:47,946 Stage-0 map = 0%,  reduce = 0%
15/04/06 22:30:47 INFO exec.Task: 2015-04-06 22:30:47,946 Stage-0 map = 0%,  reduce = 0%
15/04/06 22:30:47 WARN mapreduce.Counters: Group org.apache.hadoop.mapred.Task$Counter is deprecated. Use org.apache.hadoop.mapreduce.TaskCounter instead
Ended Job = job_1427108893685_8230 with errors
15/04/06 22:30:47 ERROR exec.Task: Ended Job = job_1427108893685_8230 with errors
15/04/06 22:30:48 INFO impl.YarnClientImpl: Killed application application_1427108893685_8230
15/04/06 22:30:48 INFO hooks.ATSHook: Created ATS Hook
15/04/06 22:30:48 INFO log.PerfLogger: <PERFLOG method=FailureHook.org.apache.hadoop.hive.ql.hooks.ATSHook from=org.apache.hadoop.hive.ql.Driver>
15/04/06 22:30:48 INFO log.PerfLogger: </PERFLOG method=FailureHook.org.apache.hadoop.hive.ql.hooks.ATSHook start=1428384648020 end=1428384648020 duration=0 from=org.apache.hadoop.hive.ql.Driver>
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
15/04/06 22:30:48 ERROR ql.Driver: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
15/04/06 22:30:48 INFO log.PerfLogger: </PERFLOG method=Driver.execute start=1428384641916 end=1428384648020 duration=6104 from=org.apache.hadoop.hive.ql.Driver>
MapReduce Jobs Launched: 
15/04/06 22:30:48 INFO ql.Driver: MapReduce Jobs Launched: 
15/04/06 22:30:48 WARN mapreduce.Counters: Group FileSystemCounters is deprecated. Use org.apache.hadoop.mapreduce.FileSystemCounter instead
Job 0:  HDFS Read: 0 HDFS Write: 0 FAIL
15/04/06 22:30:48 INFO ql.Driver: Job 0:  HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec
15/04/06 22:30:48 INFO ql.Driver: Total MapReduce CPU Time Spent: 0 msec
15/04/06 22:30:48 ERROR beeswax.BeeswaxServiceImpl: Exception while processing query
BeeswaxException(message:Driver returned: 2.  Errors: OK
converting to local hdfs://<server>/user/hue/elasticsearch-hadoop-2.1.0.BUILD.jar
Added /tmp/7bd96b68-fef6-4218-9d3d-7259f91fc095_resources/elasticsearch-hadoop-2.1.0.BUILD.jar to class path
Added resource: /tmp/7bd96b68-fef6-4218-9d3d-7259f91fc095_resources/elasticsearch-hadoop-2.1.0.BUILD.jar
Query ID = hue_20150406223030_0fa48297-19cd-45bd-aeac-0d2a349c62a3
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks is set to 0 since there's no reduce operator
Starting Job = job_1427108893685_8230, Tracking URL = http://<server>/proxy/application_1427108893685_8230/
Kill Command = /usr/lib/hadoop/bin/hadoop job  -kill job_1427108893685_8230
Hadoop job information for Stage-0: number of mappers: 0; number of reducers: 0
2015-04-06 22:30:47,946 Stage-0 map = 0%,  reduce = 0%
Ended Job = job_1427108893685_8230 with errors
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched: 
Job 0:  HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec
, log_context:45056c33-2f34-44ef-97c1-c990db391878, handle:QueryHandle(id:45056c33-2f34-44ef-97c1-c990db391878, log_context:45056c33-2f34-44ef-97c1-c990db391878), SQLState:     )
	at com.cloudera.beeswax.BeeswaxServiceImpl$RunningQueryState.execute(BeeswaxServiceImpl.java:356)
	at com.cloudera.beeswax.BeeswaxServiceImpl$RunningQueryState$1$1.run(BeeswaxServiceImpl.java:614)
	at com.cloudera.beeswax.BeeswaxServiceImpl$RunningQueryState$1$1.run(BeeswaxServiceImpl.java:603)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:356)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1574)
	at com.cloudera.beeswax.BeeswaxServiceImpl$RunningQueryState$1.run(BeeswaxServiceImpl.java:603)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by costin** [comment]
@mojaiq First off, I've added some minor formatting to the post to make it readable, I hope you'll agree it looks much better now. In the future, please do so yourself.

As for error, the logs are more extensive but still the underlying problem is hidden.

```
Ended Job = job_1427108893685_8230 with errors
15/04/06 22:30:47 ERROR exec.Task: Ended Job = job_1427108893685_8230 with errors
15/04/06 22:30:48 INFO impl.YarnClientImpl: Killed application application_1427108893685_8230
```

Can you try and see through the YARN console (or any other mechanism, Cloudera tends to have good UI with plenty of tools) what's the reason why the application which is suppose to execute the query is being killed?

From the logs it looks like the creation of the table works, the `INSERT` is sent to be executed as YARN application but the app gets killed; without any further information I can't tell what the issue.

As an alternative, can you try running the application directly from the Hive command line instead of Beeswax?

Thanks,

**Comment by mojaiq** [comment]
@costin , thanks for the suggestions and sorry for the delay in responding. The issue got resolved after upgrading to the latest build snapshot and deleting the old referenced jars.
Thanks..
